version: 2

sources:
  - name: raw
    tables:
      - name: auctions
      - name: items  # lägg till fler tabeller här om du vill
      - name: realm_data
      - name: realm_data__realms
      - name: item_media

      - name: item_details
      - name: item_details__preview_item__stats
